libgit2/rugged

README.md, ext/rugged/rugged_tree.c
Updating the README to reflect the changes in https://github.com/libgit2/rugged/commit/9dea9516208fe460293643ad601829e0d91e41c3 plus a small change to a comment for clarity.
=> Update README and comments to reflect changes to Tree::Builder

ext/rugged/extconf.rb
First, we should not check against LIBGIT2_SOVERSION, but check against the major and minor version numbers. Also, instead of hardcoding the compatible versions, we now use the minor and major version numbers from the bundled libgit2 version.
=> Automate the libgit2 compatibility check.

README.md
Branch development has already removed.
=> Revise document

ext/rugged/rugged_branch_collection.c, ext/rugged/rugged_config.c, ext/rugged/rugged_reference_collection.c, ext/rugged/rugged_remote.c, ext/rugged/rugged_repo.c, ext/rugged/rugged_tree.c, test/reference_test.rb, test/repo_test.rb
This updates to the latest libgit2 version. There is a single test failure, but that will be fixed once #469 gets merged.
This closes #468.
//cc @vmg @simonsj
=> Update to latest libgit2

CHANGELOG.md, Gemfile.lock, lib/rugged/version.rb, test/online/fetch_test.rb
Release 0.22.2. :tada: 
Fixes #480.
=> Release 0.22.2

.travis.yml, script/travisbuild
Similar to https://github.com/libgit2/libgit2/pull/3264.
=> Enable Linux Container builds on travis.

ext/rugged/rugged_remote.c, ext/rugged/rugged_submodule_collection.c
This fixes a few compiler warnings that have crept in recently.
=> Fix compiler warnings

ext/rugged/rugged_config.c, test/config_test.rb
This allows configuration changes to be performed atomically.
=> Add `Rugged::Configuration#transaction`

CHANGELOG.md, lib/rugged/version.rb
@vmg I'll tag and release this once you give your ok.
=> Release 0.23.3

ext/rugged/rugged_remote.c
Tip of `master` for libgit2 with the security fixes for XDiff.
=> XDiff upstream changes

ext/rugged/rugged_config.c
`Rugged::Config.new` can optionally take a list of paths to config files instead of a single path. In case that there is a failure while adding one of these paths to the config object, the internal `git_config` object and all related memory will not be freed.
=> Don't leak memory when opening a config file fails.

lib/rugged/version.rb
Full details in https://github.com/libgit2/libgit2/pull/3468
=> Fix ODB lookup performance

lib/rugged/version.rb
Pulls https://github.com/libgit2/libgit2/pull/3478
=> Update libgit2 with signature normalization

ext/rugged/rugged_repo.c, ext/rugged/rugged_tree.c, lib/rugged/version.rb
Courtesy of @ethomson :heart_eyes:
=> Fail merges fast

ext/rugged/rugged_tree.c, lib/rugged/version.rb
Some crazy ass shit here with the new pooled allocator and the `skip_reuc` flag. Let's try it ouuttttt
=> Experimental fast merges branch

lib/rugged/version.rb
Backports https://github.com/libgit2/libgit2/pull/3492 from libgit2
=> Fix redundant merge bases

ext/rugged/rugged_repo.c, test/remote_test.rb, test/revert_test.rb
Yet another @ethomson joint wrapped into Ruby by yours truly. Let's see how this works in practice.
=> Revert commits!

lib/rugged/version.rb
Backports https://github.com/libgit2/libgit2/pull/3542
=> Fix hard reset

lib/rugged/version.rb
This is https://github.com/libgit2/libgit2/pull/3549 -- let us see what happens in production.
=> Index fill performance improvements

lib/rugged/version.rb
Includes https://github.com/libgit2/libgit2/pull/3550
=> Index perf improvements pt2

ext/rugged/rugged_repo.c, test/repo_test.rb
As implemented by the almighty @ethomson :ok_hand:
=> The new Expand OIDs API

ext/rugged/rugged_commit.c, test/commit_test.rb
This is instead of writing it out to disk.
=> Add a way to create a commit as a buffer

ext/rugged/rugged_commit.c, test/commit_test.rb
Now you can save a commit content's to memory, sign them and give the results to rugged for it to create the commit with the correct header.
=> Add ability to create a commit with a specified signature

ext/rugged/rugged_blob.c, ext/rugged/rugged_remote.c
=> Upgrade to the latest libgit2 master

test/rebase_test.rb
Update libgit2 to https://github.com/libgit2/libgit2/pull/3808 to pull in some `git_index_read_index` fixes to eliminate some of the problems reported in #609 
/cc @arthurschreiber
=> Update libgit2 to 46082c3

lib/rugged/repository.rb
=> Grammar fixes [ci skip]

test/repo_test.rb
Full list of changes: https://github.com/libgit2/libgit2/compare/d11fcf867ba1397928fa18cf45695ff8db32ae44...a7df4a9151f09ca1f66f6267f2beb9ddf9739b73
=> Upgrade to latest libgit2

ext/rugged/rugged_blob.c, ext/rugged/rugged_patch.c, test/commit_test.rb
=> Compiler Warning fixes

ext/rugged/rugged_tree.c
This lets us execute Ruby code in parallel while making diffs.
=> Unlock GVL around `git_diff_tree_to_tree`

ext/rugged/rugged_commit.c, test/commit_test.rb
I noticed we were missing this - I think the changes are pretty straightforward.
=> Add `Rugged::Commit#summary`

test/commit_test.rb, test/diff_test.rb, test/rebase_test.rb, test/reference_test.rb, test/remote_test.rb, test/repo_test.rb, test/tree_test.rb
MiniTest 5.10 deprecated assert_equal with nil.
=> Use assert_nil instead of assert_equal

test/remote_test.rb, test/repo_test.rb
Pull in the latest libgit2 changes.
=> Upgrade libgit2

ext/rugged/extconf.rb
@arthurschreiber @carlosmn Please have a look at the individual commit messages for the details.
=> On the way to fix / improve the Windows build

ext/rugged/rugged_repo.c, ext/rugged/rugged_revwalk.c, ext/rugged/rugged_tree.c
There's no such thing as an `Iterator` in Ruby. What these methods actually return is an `Enumerator`.
=> docs: Iterator -> Enumerator

.travis.yml
Remove those lower than 2.2 and add 2.5.
=> travis: update the ruby versions to test against

ext/rugged/extconf.rb
In Debian Jessie, CMake will sometimes fail to correctly wait for the programs
it has spawned. While a proper fix would be in CMake itself, protect ourselves
from this by giving it a generous but limited time in which to run.
When it hangs, it will now instead be killed by the build process and we can try
again, instead of having to hunt down processes across machines.
---
I'm not sure how widespread this is, but on newer CMake versions the usual workaround for CMake hanging on Jessie is not working anymore. This limits the damage by actually timing out in error instead of just hanging forever.
I'm sending this as it probably doesn't hurt to have it upstream.
=> Give CMake a timeout for when it hangs

ext/rugged/rugged_config.c
Not doing so means an exception or even a break will jump over us and not give
us the opportunity to free the resources we've allocated.
I believe this is something that @tenderlove caught a while ago but apparently I forgot to send the PR.
=> config: catch exceptions during iteration

lib/rugged/version.rb
This is a security release. See the libgit2 release notes for details. https://github.com/libgit2/libgit2/releases/tag/v0.28.3
=> Update to libgit2 v0.28.3

.github/workflows/ci.yml, test/commit_test.rb, test/repo_test.rb
This includes security fixes around NTFS alternate data streams.
=> Bump libgit2 to 6777db8e834

README.md
I ran this to get the required packages, maybe others will need to also?
=> Add more help on installing pkg-config on OSX

script/travisbuild
Mostly this affects macOS where the current setup can leave us unable to contact
it.
=> ci: set up our own sshd to get more control over it

lib/rugged/version.rb
I messed up the release in a new way and the tag and gem upload don't match. This series is doomed to be forever stupid with numbers.
I'll yank the bad version once this is tagged and uploaded.
=> Update version to v1.3.2.3

lib/rugged/index.rb, lib/rugged/tree.rb
Fixes https://github.com/libgit2/rugged/issues/728
=> include_untracked_content -> show_untracked_content

lib/rugged/version.rb
Bumping libgit2 to 1.6.3 and our version number.
=> Update to 1.6.3
