ext/rugged/rugged_branch_collection.c

Currently there is no check if an exception was raised when initializing the iterator at each_branch function.

Fix SIGSEGV: check if there was an exception when initializing iterator

---

ext/rugged/rugged_repo.c

Using the tilde in the documentation for repository initialization
suggests that we perform tilde expansion in the path provided. We do no
such thing, so remove it as it's quite unlikely someone does want a
directory called '~' to have their git repos.
---
Maybe we want to have `File.expand_path('~/test/.git')` instead? The current way should go either way, this is likely the cause for #438.

Remove the tilde from the Repository documentation

---

ext/rugged/rugged.h
ext/rugged/rugged_remote.c
ext/rugged/rugged_remote_collection.c
ext/rugged/rugged_repo.c
ext/rugged/rugged_revwalk.c

This fixes a bunch of warnings coming from gcc:
* `git_push` and related functions were made private in `libgit2`, we should be using the `git_remote_push` helper function instead.
* `rugged_repo_new_with_backend`, `rb_git_walker_push_range` were recently added and introduced some gcc warnings.
* `rb_git_repo_merge_bases` and `rb_git_remote_collection_each_name` caused some gcc warnings due to type mismatches on comparisons.
This fixes all these issues and brings us back to a clean build.

Fix compiler warnings

---

ext/rugged/rugged_submodule.c
ext/rugged/rugged_tree.c

Update bundled libgit2 to v0.22.0 in preparation for a new rugged release. :tada:

Update to libgit2 v0.22.1

---

ext/rugged/rugged.h
ext/rugged/rugged_tree.c
test/tree_test.rb

This adds a new `count_recursive` method to Rugged tree objects. This counts all blobs in the tree recursively, with an optional limit to bail early. This allows asking things like "Are there more than 1 million files in this repo?" without a roundtrip into ruby for each file.

Add Tree#count_recursive

---

test/online/fetch_test.rb

~~~Looks like someone changed https://github.com/libgit2/TestGitRepository.git.~~~
See @nulltoken's comment below.

Fix failing online test cases

---

ext/rugged/rugged_note.c

This updated to the latest libgit2 changes.
We should probably bump libgit2 again after https://github.com/libgit2/libgit2/pull/3100 gets merged to fix building rugged on OS X.

Update to latest libgit2

---

ext/rugged/rugged_revwalk.c
test/walker_test.rb

Here's a new APi for `Walker` which is memory safe (i.e. frees the walker immediately and prevents used packfiles from lingering around). The walker code has been refactored to reduce duplication; old APIs should be 100% backwards-compatible.
@arthurschreiber can you fit this on the release? Thanks :)
cc @spraints who is already using this on production

Memory-safe Walker API

---

CHANGELOG.md
ext/rugged/rugged_repo.c
test/reference_test.rb
test/repo_test.rb

This allows setting and getting the identity that is used for writing reflogs.

Add setter and getter for the Repository ident.

---

Gemfile.lock
ext/rugged/rugged_blob.c
test/blob_test.rb

Pretty straightforward. Allows us to count lines on a blob without getting it into Rubyland.
cc @aroben

Implement Blob#loc

---

.travis.yml
CHANGELOG.md
Gemfile.lock
ext/rugged/rugged_diff.c
ext/rugged/rugged_index.c
ext/rugged/rugged_remote.c
ext/rugged/rugged_remote_collection.c
ext/rugged/rugged_repo.c
ext/rugged/rugged_submodule.c
test/remote_test.rb
test/submodule_test.rb

This mainly contains changes necessary to support the API changes in the `git_remote_*` API that were recently introduced.

Update to the latest libgit2 changes

---

ext/rugged/rugged_submodule.c
ext/rugged/rugged_submodule_collection.c
test/submodule_test.rb

This PR aligns the Submodule API with the new libgit2 submodule API.
I pulled out all setter methods that were available on `Rugged::Submodule` into a common `#update` method on the `SubmoduleCollection` class.

Change the Submodule API.

---

.travis.yml

Let's use whatever travis thinks are the appropriate bundler args for installation.
(At the moment, that's: `bundle install --jobs=3 --retry=3`)

Use travis defaults for bundler installation.

---

CHANGELOG.md
ext/rugged/rugged_repo.c
test/repo_test.rb

This is very handy when it's required to redirect user to resolve merge conflicts manually.

repo: support for checkout_index

---

rugged.gemspec
test/blame_test.rb
test/blob_test.rb
test/branch_test.rb
test/cherrypick_test.rb
test/commit_test.rb
test/config_test.rb
test/diff_test.rb
test/index_test.rb
test/merge_test.rb
test/note_test.rb
test/object_test.rb
test/online/fetch_test.rb
test/online/ls_test.rb
test/online/push_test.rb
test/patch_test.rb
test/reference_test.rb
test/remote_test.rb
test/repo_ignore_test.rb
test/repo_pack_test.rb
test/repo_reset_test.rb
test/repo_test.rb
test/status_test.rb
test/submodule_test.rb
test/tag_test.rb
test/test_helper.rb
test/tree_test.rb
test/walker_test.rb

Fixture Management in Rugged has gone a bit out of hand. There's multiple different ways how fixtures are handled and managed, and it's not obvious when to use what.
* `Rugged::RepositoryAccess`: Including this module opens the bare repository at `test/fixtures/testrepo.git` and assigns it to `@repo`. Any modification to `@repo` will cause other test cases to fail, so this is only used for test cases that are read-only.
* `Rugged::TempRepositoryAccess`: This creates a clone of the repository at `test/fixtures/testrepo.git` and assigns it to `@repo`. This is used by test cases that modify the repo or that need a repo with a workdir.
* `Rugged::SandboxedTestCase`: This is a test class that provides the methods `sandbox_init` and `sandbox_clone`. `sandbox_init` copies test fixtures from …

Better Fixture Management

---

test/commit_test.rb
test/patch_test.rb

our tests expect commit abbreviations to be done
with 7 characters, so instead of assuming current
machine doesn't have a global ~/.gitconfig, let's
make sure to set repository's core.abbrev to 7
on test runs.
Signed-off-by: Felipe Balbi <balbif@gmail.com>

test: make sure to set core.abbrev to 7

---

.travis.yml
lib/rugged/version.rb

This enables automatic releases and pre-releases via Travis.
Releases get cut when a new tag gets pushed to the repo and the build succeeds for the Ruby `2.2.2` build on travis. I'm thinking about automatically generating the `lib/rugged/version.rb` file based on the tag name, which would basically allow us to do release without having to bump this version identifier for each release.
Each commit that happens on the master branch will trigger the push of a pre-release gem to rubygems if the build on Ruby `2.2.2` passses. These gems will be versioned as `$version.$build_number.pre`. Using the build number is not perfect as it's not per-actual-version, but it's an increasing sequence, so if two pre-releases share the same "actual" release version, the one with the higher build number will …

Releases and pre-releases via Travis

---

.travis.yml
lib/rugged/version.rb

@arthurschreiber: I gotta roll this back because it's breaking GitHub's internal vendoring/packaging scripts. :(((((((
We'll have to continue tagging releases manually while I figure this out.

Do not automatically tag releases from Travis

---

ext/rugged/rugged.c
test/lib_test.rb

Previously I've been using regex to check the validity of a string as a full 40-character sha1, but decided to benchmark that against the `Rugged.hex_to_raw` method and found it to be ~6x faster. Only bummer was that `hex_to_raw` will raise if the input string was invalid, and in that case ended up only being about 1.5x faster.
So this extracts just the validity check and returns a boolean value. Meaning we can skip the raise/rescue slowdown as well as creating the output string that `hex_to_raw` would have made.

Add Rugged.valid_full_oid? helper method

---

ext/rugged/rugged_tree.c
test/tree_test.rb

The docs here say that with a Rugged::Tree::Builder object the remove method should return false if the file does not exist, but right now it'll actually raise a Rugged::TreeError.
Here's a test case and small fix for that.

Treebuilder remove return

---

ext/rugged/rugged_repo.c

When DB backends are successfully attached to the DB instacnes they
get freed along with the DB so we don't have to. Also, the free method
on the backends is optional so we shouldn't assume it is present.
Fixes: #524

Ensure DB backends haven't already been freed

---

ext/rugged/rugged_remote.c
test/remote_test.rb

I am using Rugged quite a bit on a project and needed a method to prune the remotes. I didn't see a way to do it in the documentation so I thought I would give it a shot myself. Here is the result.  My C-fu has long since atrophied and I have never build a C-extension before so feel free to be harsh in your review/feedback.
It also looks like it is possible to pass a `prune` option to `git_remote_fetch` but I couldn't figure out how to do it yet.

Adds Rugged::Remote#fetch(prune:)

---

ext/rugged/rugged_remote.c

This integrates https://github.com/libgit2/libgit2/pull/3411 into rugged.

Add custom headers to smart http requests

---

ext/rugged/rugged.c

This adds a few missing error classes from libgit2, namely `RevertError`, `CallbackError`, `CherrypickError`, `DescribeError`, `RebaseError` and `FilesystemError`.

Add some missing error classes from libgit2.

---

ext/rugged/rugged_tree.c

This bumps libgit2 to a589f22a9441523327e4c987c5b5f5f857472067, fixes Rugged for the API changes from that bump and adds support for the `GIT_MERGE_NO_RECURSIVE` tree merge option.
/cc @josh @aroben @vmg @ethomson

Add support for new GIT_MERGE_NO_RECURSIVE option for merges 

---

ext/rugged/extconf.rb

Insert the right libraries to link to to get WinHTTP working. These are
normally done by the build system, but we're building statically so we put
them in ourselves.
We don't write out any dependencies to pkg-config, so let's get rid of it.
To boot, it's not always installed on this platform.
---
It'd be nice to be able to build this without having to specify the dependencies manually, like we do for the other deps on unix, but pkg-config isn't really a thing on Windows (and it doesn't come in the devkit), so we kinda have to put the dependencies here.
This resolves the linking issues from #506 though the tests still fail spectacularly as files are either missing or read-only. But those are all issues with the teardown, so the actual tests are working.

Build on Windows with WinHTTP

---

.travis.yml

This adds the latest 2.3.0 release to the Travis config, updates to the latest 2.1.x and 2.2.x versions and drops the builds against 1.9.3 (which has been unsupported for quite a while).
Also change the way we specify builds for OS X and only run builds for supported versions.

Update the list of ruby versions to build on Travis

---

ext/rugged/rugged_commit.c
test/commit_test.rb

This adds `Commit#header_field`, which was added to libgit2 in https://github.com/libgit2/libgit2/pull/3240. This should make it possible to fetch and verify commit signatures in Ruby.
/cc @carlosmn @peff

Add Commit#header_field method

---

ext/rugged/rugged_commit.c
test/commit_test.rb

The `Commit#header_field` method added in #562 raises an exception currently if the header field is not present. This PR changes the method to return `nil` in this case.

Make Commit#header_field return nil for non-existent headers

---

ext/rugged/rugged_commit.c
test/commit_test.rb

This PR adds a `Commit#header_field?` method for checking if a commit has the given header.

Add Commit#header_field? for checking header existence

---

ext/rugged/rugged_commit.c
lib/rugged/commit.rb

Just some simple changes since I missed review the previous time.
`Commit#header_field?` can be implemented directly in Ruby since the C
code is almost 100% redundant.
The original `Commit#header_field` has been refactored to prevent a
possible memory leak, and to properly tag the resulting header with the
encoding of the commit message, if we know it.
There are no breaking API changes
cc @mastahyeti

commit: Cleanup header extraction APIs

---

ext/rugged/rugged_commit.c
test/commit_test.rb

This returns the signature and the signed data so the user can compare
them.
---
This depends on libgit2/libgit2#3599 so we shouldn't merge until that gets resolved.

Add Commit::extract_signature

---

lib/rugged/tag.rb
test/tag_test.rb

This adds `Rugged::Tag.extract_signature method` to extract tag signatures/signing-data from tags.
/cc @vmg @carlosmn @brianmario

Add Tag.extract_signature method

---

ext/rugged/rugged_repo.c
test/cherrypick_test.rb

This is like #cherrypick but we do it in-memory and return an index with
the result.
---
I don't love the handling of the 'mainline' param. In C we always want it, but it feels like in ruby you'd leave it out and convert that to a `0` in C which also means "I don't expect to deal with a merge".
/cc @scottjg this should get you what you need for an in-memory rebase by looping around this.

Introduce Repository#cherrypick_commit

---

test/revert_test.rb

This fixes #566 and #420 by updating to the latest version of libgit2 and adds a test case that was previously failing.

Test and fix for #566

---

ext/rugged/rugged_revwalk.c
test/walker_test.rb

When given an argument or block this method now delegates to
Enumerable#count.

Make Walker#count compatible with Enumerable#count

---

ext/rugged/rugged_commit.c
lib/rugged/tag.rb
test/commit_test.rb

This lets the caller distinguish between a missing object, the wrong
kind of object and unsigned commits.
---
Limitations you discover when actually trying to integrate into the product.

commit: raise when given bad data to extract the signature

---

ext/rugged/rugged_settings.c
test/tree_test.rb

This updates libgit2 to [`edaffe2`](https://github.com/libgit2/libgit2/commit/edaffe22a205c57022cc365ab20dcbf7e22f68c4), which turns on stricter object validation for functions like the treebuilder.  Additionally, add a `Tree::Builder` test that ensures that we throw when adding a new tree entry that is nonexistent, but that we can disable this behavior with `Rugged::Settings['strict_object_creation']`.
/cc @vmg

Strict object creation

---

lib/rugged/version.rb
test/tree_test.rb

We've been incrementing 0.24.0 as a beta since [way back in October](https://github.com/libgit2/rugged/commit/fb17354c).  Now that libgit2 is [updating to 0.24](https://github.com/libgit2/libgit2/issues/3626) themselves, update to match.

Release 0.24.0

---

ext/rugged/rugged_repo.c

Use `xmalloc` instead of `malloc`, as `xmalloc` will fail gracefully, raising an exception and [returning to Ruby itself](https://github.com/ruby/ruby/blob/5fa5b50e587918f7003a9a6579e655896e82aa2d/eval.c#L589) while `malloc` will merrily carry-on and we will doubtless try to dereference a null pointer.

ext: Use `xmalloc` instead of `malloc`

---

ext/rugged/extconf.rb

On Windows, Ruby-DevKit is MSYS based. As such we should use MSYS
Makefiles with CMake. Otherwise it might happen that CMake picks a
gmake.exe from somewhere instead of make.exe from Ruby-DevKit as CMake
seems to prefer gmake over make.
In a concrete case, when doing "gem install rugged" on Windows with
Strawberry Perl installed and in PATH, CMake was picking
C:/Strawberry/c/bin/gmake.exe
instead of
C:/Ruby-DevKit/bin/make.exe
While the latter is linked against MSYS-1.0.DLL and understands Unix-style
paths on Windows, the first is a native Windows executable linked against
MSVCRT.DLL that does not. This resulted in path mangling issues leading to
CMake's "Detecting C compiler ABI info" step to fail because the helper
executable failed to build, which in turn led to CMAKE_SIZEOF_VOID_P not …

extconf: Use MSYS Makefiles with CMake on Windows

---

ext/rugged/rugged_rebase.c
lib/rugged/version.rb
test/rebase_test.rb

The plan is to tag and release 8552038 as v0.25.0b2, and then merge these changes into master.

Prepare for v0.25.0b2

---

ext/rugged/rugged.h
test/reference_test.rb

We should be tagging oids as US-ASCII (or UTF-8).  We know the encoding
of the bytes in that string, so we should be indicating that encoding to
clients of the library.

Tag oids as US_ASCII

---

ext/rugged/rugged_rebase.c
test/rebase_test.rb

Right now, Rugged will throw a `Rugged::RebaseError` when trying to commit an empty rebase patch. This error type can also be thrown for a bunch of other error conditions, which leaves consumers testing for the error's `message` to distinguish between these different error types.
Let's introduce a new exception class instead.
/cc @vmg @ethomson @carlosmn

Rebase: Better error handling in case of empty patches.

---

ext/rugged/rugged.c
test/lib_test.rb

Tag return value of `Rugged.raw_to_hex` as US-ASCII.

---

ext/rugged/rugged_rebase.c

This makes it match the style that is used elsewhere in Rugged and in MRI.

Update the rebase documentation.

---

ext/rugged/rugged_tree.c
test/tree_test.rb

Bump libgit2 now that we trust it a bit more, and add the more efficient tree updater method.
I've tried to make the docs clear, but I dunno, I'd appreciate pointers if it can be made better.

Bump libgit2, include tree updater

---

test/rebase_test.rb

Inmemory rebases seem to be losing files. Add two examples that show a successful rebase and a (failing) inmemory rebase.

Show that inmemory rebase is losing files

---

script/cibuild

If you're running `script/cibuild` yourself, from an actual tty,
then `git log` will by default invoke your pager.

script/cibuild: add --no-pager when logging

---

test/config_test.rb
test/lib_test.rb

Mutating `Rugged::Settings` will impact other tests, specifically
`test_read_global_config_file`.  This commit restores global settings so
that other tests aren't impacted.
I found the `test_search_path` and `test_read_global_config_file` pair
by using `minitest-bisect`.  First I looked up the failing seed on
Travis, which was `--seed 43037`.  Then I ran this:
```
$ minitest_bisect -Ilib:test --seed 43037 test/*_test.rb
```
It found the failing test pair, and I was able to verify the fix by
doing:
```
$ rake test TESTOPTS=--seed=43037
```

Fix random test failure

---

ext/rugged/rugged_index.c
test/index_test.rb

Previously this required that the custom labels (for ours, theirs, and ancestor) were fixnums instead of strings, which contradicts the docs (and doesn't make a lot of sense :smiley: ).

Fix Index#merge_file with custom labels

---

ext/rugged/rugged_patch.c
test/diff_test.rb

Similar to `Rugged::Diff::Patch#lines`, this returns the number of bytes in the patch text.
It accepts 3 optional boolean, keyword arguments:
* `include_context` - include context lines in the byte count
* `include_hunk_headers` - include hunk header lines in the byte count
* `include_file_headers` - include file header lines in the byte count
This needs inline-documentation written still but wanted to get this open for review early in case any changes to the API will mean only writing the docs once.

Add Rugged::Diff::Patch#bytesize

---

ext/rugged/rugged_patch.c
test/diff_test.rb

This is related to https://github.com/libgit2/rugged/pull/622 which added the `Rugged::Patch#bytesize` - which itself accepts options for what to include in the counts.
But, since `Rugged::Patch#lines` already existed and included the _total_ counts of context, addition and deletion lines - the options added to that method here are **exclusionary**. Meaning by default this method will continue to return the same value it always has, unless  you specify otherwise.
This feels annoyingly inconsistent with `Rugged::Patch#bytesize` but unless we're willing to break the API I'm not sure what else to do ;)
Thoughts?

Change Rugged::Patch#lines to accept count exclusion options

---

ext/rugged/rugged_patch.c
test/diff_test.rb
test/patch_test.rb

I ran across an issue in `Rugged::Patch#lines` where the current implementation completely ignores the EOF newline markers, as it only sums up additions, deletions and context lines.
Also, it looks like @brianmario only applied documentation changes to `Rugged::Patch#bytesize` when aligning it with `Rugged::Patch#lines`, but did not modify the code. :trollface: (And I failed to see that during review).
This fixes both these issues. 👍

Fix `Rugged::Patch#lines` and `Rugged::Patch#bytesize`

---

ext/rugged/rugged_patch.c
test/patch_test.rb

In some cases we might want to only generate the header of a `Rugged::Patch`, not the whole output.

Add `Rugged::Patch#header`

---

ext/rugged/rugged_index.c
test/index_test.rb

libgit2's `git_merge_file` expects and `ours` and a `theirs` side so that it can either automerge the two, or if that fails, produce a merge file with conflicts marked up.  It cannot produce anything if the ours or the theirs side is missing.  (libgit2 in fact `assert`s here.)
Raise an error in this situation instead of trying to call `libgit2` where it will undoubtedly crash.

Index.merge_file: raise when conflict is missing one side

---

ext/rugged/extconf.rb

extconf: Explicitly link against zlib on Windows to fix the build

---

ext/rugged/rugged.c
ext/rugged/rugged.h
ext/rugged/rugged_blob.c
ext/rugged/rugged_index.c
test/blob_test.rb

We have `Rugged::Index.merge_files` that will produce the results of a three-way merge for a conflict.  (It looks up the conflict in the index and passes the three sides to `xdiff`).
Provide a similar function that will take the file contents directly (either as a string, or with an oid) and perform the three-way merge and return the results.
Note that this function will accept either input as a string _or_ the given object ID of a blob to lookup and merge.  This may be a bit overwrought, TBH, as most callers probably only want to deal with oids...?
/cc @brianmario

Introduce `Rugged::Blob.merge_files`

---

ext/rugged/rugged.h
ext/rugged/rugged_remote.c
ext/rugged/rugged_repo.c
test/online/fetch_test.rb

This exposes the `certificate_check` callback for `Rugged::Remote#fetch`.
It is based on #571, but changes the `valid` parameter to be `true` or `false` instead of `1` or `0`, and cleans up some of the code and the test cases.
Fixes #571.

Remote: Expose `certificate_check` callback

---

test/diff_test.rb

I would like to start refactoring `Rugged::Diff.diff`, but we are
missing tests for some of the branches in the C code.  This commit adds
tests for those branches.
I wasn't sure where to put these tests, so I just made a new test class.

Add regression tests for error cases on `Rugged::Diff.diff`

---

ext/rugged/rugged_tree.c

If `Rugged::Tree.diff` can't unwrap the repository object passed in, it
can leak memory allocated in `rugged_parse_diff_options`.  Before this
commit, memory usage for this script will grow unbounded:
```ruby
require 'rugged'
loop do
begin
Rugged::Tree.diff nil, nil, nil, { paths: ['x' * 90] }
rescue TypeError
end
end
```
To fix this, just try to unwrap the repository object before calling
`rugged_parse_diff_options`.

Fix memory leak in `Rugged::Tree.diff`

---

ext/rugged/rugged_commit.c

RDoc / YARD wants classes to be referenced by their non-qualified name.

Fix two tiny documentation issues.

---

ext/rugged/rugged_tree.c
test/diff_test.rb

Looks like this issue got introduced when the internals of `Rugged::Tree.diff` were refactored.
I added a test case and fixed the underlying issue.

Fix `Rugged::Tree.diff` with first tree being `nil`

---

ext/rugged/rugged_tree.c
test/merge_test.rb

The default for rename detection for merge operations changed in the latest libgit2 version from being disabled to being enabled. This change allows users to specify `renames: false` to disable this detection.

Allow disabling rename detection for merge operations.

---

lib/rugged/version.rb

Bump the vendored libgit2 to 45d55797b661085f7f5385d748d930a5148160cd, which includes a fix around rename detection with submodules.
(Bump the version number as well.)
/cc @arthurschreiber

Bump libgit2 to 45d55797b661085f7f5385d748d930a5148160cd

---

ext/rugged/rugged.c

Sorting options were changed in libgit2.
See https://github.com/libgit2/libgit2/commit/82d4c0e6b841ae0e466bd97ab1faec0920a6b7a2.

Update comments describing sorting options

---

README.md

i think it would be helpful to find the installation instructions of the readme in case of the `ERROR: CMake is required to build Rugged.`. 
i just bundle installed a new repo and it failed with this error, so it's not apparent that one has to look into how to install rugged properly. i eventually found [this stackoverflow answer](http://stackoverflow.com/a/36587267/100731) but not the readme itself via google.

add a little hint in the readme for google

---

ext/rugged/rugged_signature.c
test/commit_test.rb

When creating a commit, with a typo in `:email` key in the `:author` hash, I got an error message that didn't immediately tell me what the problem was:
> TypeError: wrong argument type nil (expected String)
With a tiny change, we can get Ruby to generate a far more understandable error message if an `:email` or `:name` is not supplied.
> KeyError: key not found: :email

Use Hash#fetch instead of Hash#[] for more understandable error messages

---

ext/rugged/rugged.c
ext/rugged/rugged.h
ext/rugged/rugged_signature.c
test/signature_test.rb

I'm not sure if `signature_from_string` or `parse_signature` would be more appropriate for ruby.
/cc @brianmario

Add a method to parse a signature from a buffer

---

README.md

fix bad character in README

---

ext/rugged/rugged_remote.c

The strings themselves are owned by the ruby runtime. We must only free the
array we allocated to point to their buffers.

remote: do not free the custom header ruby strings

---

ext/rugged/rugged_repo.c
lib/rugged/repository.rb

I think this will make other changes like in #701 much easier, and
removes some branching code from C.

Move Rugged::Repository#status to Ruby

---

ext/rugged/rugged_settings.c
test/settings_test.rb

This commit adds two methods to `Rugged::Settings`:
* Rugged::Settings.max_cache_size
* Rugged::Settings.used_cache_size
`max_cache_size` returns the maximum size the internal libgit2 caches
will consume, and `used_cache_size` is the size the cache is currently
consuming.
I realize we already have `Rugged::Settings[]`, but `GIT_OPT_GET_CACHED_MEMORY` returns two values.  Returning an Array seems unhelpful because end users won't know what the elements mean.  Returning a struct instance would be more descriptive for end users, but allocating an object feels like a waste.  I could have introduced two new string parameters to `Rugged::Settings[]`, but I think string parameters aren't that great for API discoverability.  OTOH, all other settings are done via `Rugged::Settings[]`.  I …

Add reader methods for cache information

---

ext/rugged/rugged_index.c

The "VALID" flag in git refers to the "assume-unchanged" feature, such
that if, in a non-bare repository, an index entry is marked as "VALID",
the git CLI (e.g. `git status`) will assume that the file never changes,
and ignore any changes that do occur.
See https://github.com/libgit2/rugged/issues/636 for the issue and research leading to this change.
I wasn't able to track down a good way of unit testing this change, as
these flags aren't really exposed in Rugged, and I didn't notice any tests
working on non-bare repositories.

Don't default index entries to "VALID"

---

ext/rugged/rugged_commit.c
ext/rugged/rugged_config.c
test/commit_test.rb

This wraps the new [trailer parsing API](https://github.com/libgit2/libgit2/pull/4451) up in a new method `Rugged::Commit#trailers`. The return value is an array of arrays like so:
```
[
["Trailername", "value"],
...
]
```
The idea here is to maintain the order the parser saw the trailers, and let the caller merge them into a hash if they don't care about the order.
We're still working on getting the libgit2 side merged for this, but this side shouldn't require any changes once that's ready.
cc @charliesome @arthurschreiber

Wrap trailer parsing API

---

.yardopts

Many people (including me) use the yard documentation available over http://www.rubydoc.info/github/libgit2/rugged to look up API documentation for rugged.
Unfortunately, YARD has some problems understanding the class hierarchy for the classes defined in C. But we can fix this by telling yard to parse the `ext/rugged/rugged_object.c` and `ext/rugged/rugged_reference.c` files before the other source files.
This is a bit unfortunate, because for subclasses like `Rugged::Blob`, all the methods inherited from `Rugged::Object` are not mentioned or linked at all.
---
This is how the documentation looks like before the config change:
You can see that the superclass for `Rugged::Blob` is called `RuggedObject` and not linked correctly.
---
This is how it looks like after the change:
Here you can …

Help YARD parse files in the correct order.

---

ext/rugged/rugged_config.c
test/config_test.rb
test/fixtures/testrepo.git/config

This method allows you to fetch all values for a particular config,
similar to `git config --get-all "remote.origin.fetch"`.
For example, I have a git config with two `fetch` settings in one
remote:
```
$ cat ~/git/uart/.git/config
[core]
repositoryformatversion = 0
filemode = true
bare = false
logallrefupdates = true
ignorecase = true
precomposeunicode = true
[remote "origin"]
url = git@github.com:tenderlove/uart.git
fetch = +refs/heads/*:refs/remotes/origin/*
fetch = +refs/heads/*:refs/remotes/lololol/*
[branch "master"]
remote = origin
merge = refs/heads/master
```
With `Rugged::Config#get_all` I can get the list of `fetch` options from
the config:
```
$ ruby -I lib -rrugged -e'p Rugged::Repository.new("/Users/aaron/git/uart").config.get_all("remote.origin.fetch")' …
```

Add Rugged::Config#get_all

---

ext/rugged/rugged.c
ext/rugged/rugged.h
ext/rugged/rugged_allocator.c

This lets us tell the ruby runtime how much memory rugged/libgit2 is allocating to give it a more realistic view of how much memory the process is using.
The expectation/hope is that long-lived processes will give back memory to the system more readily than is currently the case.
---
This is something which was spoken about at the contributors' summit as a likely source of server-side processes using rugged taking up silly amounts of memory.
/cc @arthurschreiber who suggested this

Set a custom allocator to redirect via the ruby runtime

---

ext/rugged/rugged_blob.c
ext/rugged/rugged_repo.c
test/repo_test.rb

Rugged is currently too strict in not recognizing objects that `respond_to? :to_path`. In particular, this means we can't pass a `Pathname` object directly, contrary to all builtin methods accepting paths for example.
This PR fixes the cases.
I simply searched for all `Check_Type(.*_path, T_STRING)`, so I may have missed some.

Support Ruby's convention for pathnames and Pathname lib

---

ext/rugged/rugged.c
ext/rugged/rugged.h
test/dotgit_test.rb

These can be used to see whether a file would be read as `.gitignore` or
`.gitattributes` when read from the filesystem.

Expose methods to detect .gitignore and .gitattributes files

---

ext/rugged/rugged_repo.c
test/status_test.rb

When we call the block, an exception or even a call to `break` would cause us to
unwind the stack and skip any resource freeing that we may have. The solution is
to call `rb_protect` which will let us catch the exception and raise whenever we
need to.
Doing this as part of a `git_status_foreach` is unnecessarily awkward so move to
iterating over the status list ourselves and free the entry list as soon as we
notice there was an exception.
For example, this program will consume memory
indefinitely:
require 'rugged'
repo = Rugged::Repository.new ARGV[0]
loop do
repo.status do |file, status_data|
break
end
end
Thanks to Aaron Patterson for discovering this and the original hacky fix.
---
This solves the same problem as #715 but in a less hacky and future-anti-proofing way.
/cc @tenderlove …

repo: catch exceptions when iterating through status

---

ext/rugged/rugged.h
ext/rugged/rugged_remote.c
ext/rugged/rugged_repo.c
test/repo_apply_test.rb

Initial support for the `git_apply` functionality added to `libgit2` in https://github.com/libgit2/libgit2/pull/4705/. This is my first time working on `rugged`, so I'm happy to do whatever is needed to get this PR up to standards for the project.
Call signature: `Repository#apply(diff, options = {})`.
Options:
```
:location - Whether to apply the changes to the index, the working directory, or both. Valid values: :index, :workdir, :both. Defaults to :both.
```
At the moment, `#apply` returns `true` on success. On failure, an exception will be thrown (because of the call to `rugged_exception_check(error)`), which means in practice `false` will never be returned. I thought about returning the modified index instead, but that doesn't make sense given the possibility of modifying only the …

Add Repository#apply

---

ext/rugged/rugged_diff.c
ext/rugged/rugged_repo.c
test/diff_test.rb

This PR exposes libgit2's `git_diff_from_buffer(git_diff **out, const char *content, size_t content_len)` [function](https://github.com/libgit2/libgit2/blob/master/src/diff_parse.c#L68-L107) in rugged by adding a class method `Rugged::Diff::from_buffer(buffer)`. This allows for creating Rugged::Diff objects from patches in String format. Please have a look at the code and let @dometto and myself know if this PR is on the right track.
BTW, one peculiar thing we noticed while writing the tests for this PR is that `git_diff_from_buffer` rejects patches that are created with `Rugged::Repository#diff(left, right, options={})` if either `left` or `right` is set to `nil`. According to [the test suite](https://github.com/libgit2/rugged/blob/master/test/diff_test.rb#L108-L157) this is allowed, but …

[Feature] Expose libgit2's git_diff_from_buffer in rugged through Rugged::Repository#diff_from_buffer(buffer)

---

ext/rugged/rugged_diff.c

I use strict compiler flags on my version of Ruby.  Since the callback
signature didn't match correctly, compilation would fail.  This fixes
the nogvl callback signature.

Unlock GVL callback should be `void *(*)(void *)`

---

ext/rugged/rugged_config.c
ext/rugged/rugged_diff.c
ext/rugged/rugged_repo.c
lib/rugged/version.rb
test/status_test.rb

It includes a couple of leaks in case of error and a warning fix which could make you fail to compile if you have strict mode.

Bump libgit2 to v0.28.2 and backport some fixes

---

ext/rugged/rugged_blob.c
ext/rugged/rugged_commit.c
ext/rugged/rugged_index.c
ext/rugged/rugged_note.c
ext/rugged/rugged_object.c
ext/rugged/rugged_rebase.c
ext/rugged/rugged_repo.c
ext/rugged/rugged_tag.c
ext/rugged/rugged_tree.c

This lets us provide more information to the ruby VM about what our objects look
like including information about how much memory they use up.

Use TypedData when wrapping library objects

---

.travis.yml
lib/rugged/version.rb

This is a security release. See the libgit2 release notes for details. https://github.com/libgit2/libgit2/releases/tag/v0.27.9

Update to libgit2 v0.27.9

---

lib/rugged/version.rb

Both the v0.28.3 tag and uploaded gem were wrong, in different ways. The tag
pointed to v0.28.2 and the gem was made off of master.
Bump the version so we can create a new tag and upload.

Bump version to v0.28.3.1

---

.github/workflows/ci.yml
.travis.yml
script/travisbuild

Build the main portion on Actions. This gives us particularly a speedup on macOS builds. I've kept the `ruby-head` on Travis as it's more convenient there for the moment.

Move the bulk of CI to Actions

---

ext/rugged/rugged_diff.c

The GVL changes were found to cause lockups in the Ruby VM causing systems to become unresponsive.
We were not able to catch one of these lockups such that we could inspect the state of the VM but as it's causing the process to lock, we're going to have to revert until a safer version is presented.
/cc @tenderlove 
/cc @stanhu FYI

Revert patch generation GVL changes

---

ext/rugged/rugged_repo.c

Fixes https://github.com/libgit2/rugged/issues/819.

Ensure exception is initialized, in case nentries is zero.

---

ext/rugged/extconf.rb
rugged.gemspec

This pull request addresses two issues preventing rugged 0.28 from installing successfully on Windows:
- `pgroup` is not available on Windows (the alternative is `new_pgroup`)
- The mingw `libssh2` package, which is required for building rugged, is not installed out of the box on RubyInstaller with MSYS2

Fix Windows builds

---

.github/workflows/ci.yml

We constantly are fighting updating these minor versions because rbenv wants us
to be precise. But the ruby-setup action we rely on for the Ubuntu builds
has a much more restricted list of versions which are available.
Keeping both as the same list means CI breaks constantly for no reason so create
two different lists to try to stop us having to do busywork.

ci: be less precise with our ruby version with setup-ruby

---

ext/rugged/rugged_config.c
test/config_test.rb

Previously keys where returned in nested arrays i.e. `[["user.email"]...]` this returns the behavior to just returning keys
The behavior changed in #803 likely due to a copy paste mistake. This returns this to the previous behavior

each_key returns individual keys not wrapped in an internal array

---

lib/rugged/commit.rb
lib/rugged/repository.rb
lib/rugged/submodule_collection.rb
test/online/fetch_test.rb
test/rebase_test.rb
test/reference_test.rb
test/tag_test.rb

Ruby 2.7 is raising a bunch of,
`warning: Using the last argument as keyword parameters is deprecated`
warnings. we can resolve these these by using ** when we intend that last argument to be kwargs.

Remove ruby 2.7 warnings

---

ext/rugged/rugged_remote.c
ext/rugged/rugged_repo.c

Add proxy support for clone and remote operations.
This utilizes the non-libcurl proxy support added to libgit2 in libgit2/libgit2#4870
Hoping this will address #440
Looking for input on the API (Should this live in an option?) and help with how I should write tests for this.
cc @Fryguy @NickLaMuro
Also @tenderlove saw you in some commits :wave:

Add http proxy support

---

lib/rugged/version.rb

There's several bugfixes released in v1.0.1, so Rugged should upgrade and probably pull a release itself. The most important fix is that cloning from Google Source now works again.

Upgrade libgit2 to v1.0.1

---

lib/rugged/commit.rb
test/diff_test.rb

this was broken by https://github.com/libgit2/rugged/commit/9bea4004984b9ed60741b4bdff5d32454ed76132 which neglected to handle the case where _no_ arguments are passed at all (not just nothing to diff against).

fix default arguments for Commit#diff when nothing is passed

---

LICENSE
README.md

A small update to indicate the copyright isn't just for 2016 and make it clearer that we don't have an in-memory backend in this codebase.
Closes #862 
Closes #681

Updates for LICENSE and README

---

ext/rugged/rugged.c
ext/rugged/rugged_object.c
ext/rugged/rugged_repo.c

With Ruby 3.0 we're getting a warning about using `rb_cData` so let's move to `rb_cObject`. By the same, `rb_iterate` was superseded by `rb_block_call` all the way back in Ruby 1.9 so let's move forward while avoiding some warnings during compilation.

Move away from some deprecated structures

---

rugged.gemspec

This adds MINGW package as an additional dependency on Windows.
With this addition in the gemspec the rugged gem installs on a plain RubyInstaller setup.

Add dependency to cmake on Windows

---

script/travisbuild
test/config_test.rb
test/test_helper.rb

It doesn't actually make much sense to rely on whatever Git configuration exists on the system we're running on. It could have anything in there.
Set up a sandboxed empty dir for us to look up above-local configuration and set it up where we do need it.

Isolate the configuration in the tests

---

test/online/clone_test.rb
test/online/fetch_test.rb
test/online/ls_test.rb
test/online/push_test.rb
test/remote_test.rb
test/test_helper.rb

The `check_connection` test is failing as user/pass combinations are no longer allowed. Change it to be use the CI-provided network endpoint which also avoids having to figure out if we can access the Internet.
While here, I noticed a lack of `S`s on the output and so I went ahead and changed these definition-time skips to be actual skips so we can see when calling the tests that there are tests which we are skipping, instead of hiding them and pretending that all tests ran fine.

Use the local ssh for `check_connection` and stop hiding online `skip`s

---

.github/workflows/ci.yml
Gemfile
test/online/fetch_test.rb
test/online/push_test.rb

Currently macOS is using rvm as the previous `actions/setup-ruby` did not work
there at the time were building this. This change should speed up and unify the
versions we run for our tests.

ci: use ruby/setup-ruby for both builds

---

ext/rugged/extconf.rb

`Dir.exists?` has been deprecated since Ruby 2.2 and is being removed in Ruby 3.2

Use Dir.exist? instead of Dir.exists?

---

lib/rugged/version.rb

Mostly so we can release a version that will already work with ruby 3.2.

Bump version to 1.3.1

---

ext/rugged/rugged_remote.c

We needed the option to provide a `pb_parallelism` value to libgit2 when pushing a remote, so this PR adds that ability.

Allow setting pb_parallelism for remote push

---

ext/rugged/rugged_config.c
test/config_test.rb

If you don't specfiy a value for a line of configuration, the library deals with
this by storing a `NULL` value for it. We must be ready for it to appear.
Change the `#each_pair` and `#to_hash` methods to handle this and avoid
dereferencing the `NULL` pointer.

config: deal with an empty value for a malformed config file

---

ext/rugged/extconf.rb
lib/rugged/version.rb
test/repo_test.rb

The test checking the `update_tips` behaviour is failing due to a regression upstream. There is a patch available in libgit2/libgit2#6226 so we may need to update to something in the mainline depending on how that goes.

Update libgit2 to v1.4.2

---

ext/rugged/rugged_repo.c

> ℹ️ Note: I'm basing this against `maint/v1.4` because that seems to be the branch the latest version of Rugged is from, and `master` is currently behind. I can change the base on this PR once `master` is back up to date.
Some git servers, namely Azure DevOps, don't treat PATs like normal git auth credentials. Azure DevOps specifically requests [providing the PAT as an auth header](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops&tabs=Linux#use-a-pat) when doing actions like git clone. There used to be a workaround that allowed providing the path in the URL for the repo, but that also recently broke for Azure DevOps Server (the on-premises version) and the official guidance is that the header is now the only …

Supply custom headers in calls to clone_at

---

lib/rugged/tree.rb
test/tree_test.rb

It is possible to call `walk` and `each` without block and get an `Enumerator`, unlike methods `each_blob`, `each_tree`, `walk_blobs` and `walk_trees`.

allow tree methods to return Enumerator when called without block

---

.github/workflows/ci.yml
.travis.yml
ext/rugged/rugged.c
test/commit_test.rb
test/test_helper.rb

It includes a fix for the behaviour of libgit2 where it now checks ownership of a parent repository as part of  changes to address [CVE 2022-24765](https://github.blog/2022-04-12-git-security-vulnerability-announced/).

Update libgit2 to 639702

---

lib/rugged/version.rb
script/travisbuild
test/remote_test.rb
test/test_helper.rb

This updates to a version which provides compatibility with git's changes to address [CVE 2022-24765](https://github.blog/2022-04-12-git-security-vulnerability-announced/).
libgit2 and its bindings are not affected as they do not execute programs.

Update to libgit2 v1.3.1

---

lib/rugged/version.rb
script/travisbuild
test/remote_test.rb
test/test_helper.rb

This updates to a version which provides compatibility with git's changes to address [CVE 2022-24765](https://github.blog/2022-04-12-git-security-vulnerability-announced/).
libgit2 and its bindings are not affected as they do not execute programs.

Update to libgit2 v1.4.3

---

.github/workflows/ci.yml
Gemfile
ext/rugged/extconf.rb
lib/rugged/version.rb
test/online/fetch_test.rb
test/online/push_test.rb

Due to the odd way 1.3.1 was tagged and released (lack of maintenance branch and a version not matching the libgit2 one) we missed out on some changes from that version here.
These are not functional changes so it's not so bad, but we should still want the compatibility fixes for newer rubies to be taken into consideration, so let's add a 1.3.2.1 version with these fixups, like we should have done instead of 1.3.1.

Fixups for the 1.3 maintenance series

---

ext/rugged/rugged_settings.c
test/lib_test.rb

libgit2 exposes the ability to globally enable fsyncing of Git objects
via the `GIT_OPT_ENABLE_FSYNC_GITDIR` option, but we provide no way of
actually setting this value in Rugged. Add this ability via a new
"fsync_gitdir" option.

settings: add ability to enable fsyncing of Git objects

---

lib/rugged/version.rb

The rugged version number continues to be silly due to some issues we had previously.

Update to libgit2 v1.3.2

---

README.md
ext/rugged/extconf.rb

Make it simpler to install rugged with SSH support via bundler by adding a `--with-ssh` build option which can be set by `bundle config build.rugged`
https://github.com/libgit2/rugged/issues/926

Add a --with-ssh build flag to set USE_SSH=ON

---

ext/rugged/rugged_remote.c
script/travisbuild
test/online/push_test.rb

This turned off by default in the library so we've been running without SSH tests.

ci: enable SSH support

---

ext/rugged/extconf.rb

It takes extra time for something we're not going to use and in at least one
case it looks like the CLI might have some issues linking correctly.
This should fix #932 by not building the CLI which is the portion that was causing an issue though a proper fix probably still needs to happen.

extconf: do not build libgit2 tests or CLI

---

ext/rugged/rugged_blame.c
ext/rugged/rugged_blob.c
ext/rugged/rugged_commit.c
ext/rugged/rugged_config.c
ext/rugged/rugged_diff.c
ext/rugged/rugged_index.c
ext/rugged/rugged_patch.c
ext/rugged/rugged_rebase.c
ext/rugged/rugged_reference.c
ext/rugged/rugged_remote.c
ext/rugged/rugged_repo.c
ext/rugged/rugged_revwalk.c
ext/rugged/rugged_submodule.c
ext/rugged/rugged_tag.c
ext/rugged/rugged_tree.c

This fixes the `warning: undefining the allocator of T_DATA class Rugged::Commit` warnings that are common in ruby 3.2 builds
Ruby no longer wants people using the default alloc if they `Data_Wrap_Struct` it.
ruby discussion: https://bugs.ruby-lang.org/issues/18007

Remove alloc from defined classes

---

ext/rugged/rugged_revwalk.c
test/walker_test.rb

We accept objects instead of their string oid but we were using `Data_Get_Struct` instead of the `TypedData_Get_Struct` we moved to use so this conversion from `VALUE` to `git_object*` would always fail.
Fixes #860

Fix pushing/hiding objects into the walker

---

ext/rugged/extconf.rb

after **libgit2** update to `1.5` in defines of `LIBGIT2_VER` [added more spaces](https://github.com/libgit2/libgit2/blob/fbea439d4b6fc91c6b619d01b85ab3b7746e4c19/include/git2/version.h#L16-L20), so old regexp not works anymore

extconf: fix regexps for use-system-libraries

---

.github/workflows/ci.yml
script/travisbuild
test/online/push_test.rb

The library does not run these tests as there seems to be some issues around the current libssh2 and I don't know how to configure macOS CI to use a different version. There is no hope of these tests passing until the library's tests pass.

ci: do not run SSH tests on macOS

---

ext/rugged/rugged_allocator.c
lib/rugged/version.rb

Unfortunately we segfault but I'm not sure if this is something in rugged or libgit2 or elsewhere. We still segfault even without the custom allocator setup so presumably it's not something inside rugged.
Deeper testing would have to go through building a custom ruby that uses the system allocator so valgrind or gdb can see what is going on. Running a single test doesn't trigger this so it seems to be something larger, and it fails with a NULL pointer dereference somewhere deep in fileutils during the helper, which is quite odd.

Update to 1.7.1

---

.github/workflows/ci.yml
script/travisbuild
test/online/push_test.rb

This is #969 cherry-picked on top of the `maint/v1.6` branch.

ci: disable SSH tests on macOS for the 1.6 branch
